# Import Libraries

In [1]:
import numpy as np

In [2]:
from time import process_time

# List vs Numpy - Time Taken

## Time Taken By a List

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0010769999999999946


In [4]:
np_array = np.array([i for i in range (10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0026770000000000405


# Numpy Arrays

In [80]:
#  Lists

list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [84]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

# Creating 1-dimensional Array

In [87]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [91]:
a.shape

(5,)

# Creating 2-dimensional Array

In [94]:
b = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [96]:
b.shape

(2, 5)

In [102]:
c = np.array([(1,2,3,4,5),(6,7,8,9,10)],dtype = float)
print(c)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


# Initializing Placeholders in Array

In [105]:
# Creating a numpy array of zeros

x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [107]:
# Creating a numpy array of ones

x = np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [109]:
# Array of a particular value

z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [111]:
# Create an identity matrix

a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [113]:
# Create a numpy arrays with random values

b = np.random.random((3,5))
print(b)

[[0.75741749 0.6977973  0.57303618 0.8251263  0.41369955]
 [0.02903684 0.66510793 0.86449241 0.14530031 0.59607659]
 [0.86046917 0.73863105 0.61312781 0.58898841 0.39600552]]


In [125]:
# Create a random integer values array within a specific range

y = np.random.randint(10,100,(3,5))
print(y)

[[53 68 75 51 93]
 [57 99 86 59 71]
 [43 88 34 89 47]]


In [129]:
# Creating an array of an evenly spaced values --> specifying the steps

e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [133]:
# Convert a list to a numpy array

list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

# Analysing a Numpy Array

In [138]:
c = np.random.randint(10,90,(5,5))
print(c)

[[21 51 81 41 48]
 [56 64 21 72 80]
 [66 81 78 32 34]
 [85 83 29 15 77]
 [23 63 20 41 31]]


In [140]:
# Array Dimension

print(c.shape)

(5, 5)


In [142]:
# Number of Dimensions

print(c.ndim)

2


In [144]:
# Number of elements in the array

print(c.size)

25


In [146]:
# Checking the datatypes of the values in the array

print(c.dtype)

int64


# Mathematical Operation on a Numpy Array

In [151]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) #concatenate two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [153]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [155]:
print(a)
print(b)

[[1 6 5]
 [1 1 1]
 [0 8 8]]
[[13 15 13]
 [13 16 10]
 [18 14 12]]


In [157]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[14 21 18]
 [14 17 11]
 [18 22 20]]
[[-12  -9  -8]
 [-12 -15  -9]
 [-18  -6  -4]]
[[ 13  90  65]
 [ 13  16  10]
 [  0 112  96]]
[[0.07692308 0.4        0.38461538]
 [0.07692308 0.0625     0.1       ]
 [0.         0.57142857 0.66666667]]


In [159]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [161]:
print(a)
print(b)

[[3 2 9]
 [6 0 7]
 [9 5 5]]
[[14 11 16]
 [14 15 12]
 [14 12 15]]


In [163]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))
print(np.multiply(a,b))

[[17 13 25]
 [20 15 19]
 [23 17 20]]
[[-11  -9  -7]
 [ -8 -15  -5]
 [ -5  -7 -10]]
[[0.21428571 0.18181818 0.5625    ]
 [0.42857143 0.         0.58333333]
 [0.64285714 0.41666667 0.33333333]]
[[ 42  22 144]
 [ 84   0  84]
 [126  60  75]]


# Array Manipulation

In [168]:
array = np.random.randint(0,10,(5,5))
print(array)
print(array.shape)

[[2 1 8 1 6]
 [7 6 0 4 3]
 [4 0 6 3 6]
 [4 6 5 4 7]
 [1 3 5 2 4]]
(5, 5)


In [172]:
# Transpose

trans = np.transpose(array)
print(trans)
print(trans.shape)

[[2 7 4 4 1]
 [1 6 0 6 3]
 [8 0 6 5 5]
 [1 4 3 4 2]
 [6 3 6 7 4]]
(5, 5)


In [174]:
array = np.random.randint(0,10,(5,5))
print(array)
print(array.shape)

[[1 0 5 6 7]
 [0 5 4 0 6]
 [3 9 3 4 3]
 [6 1 1 0 0]
 [7 0 4 1 1]]
(5, 5)


In [176]:
trans2 = array.T
print(array)
print(trans2.shape)

[[1 0 5 6 7]
 [0 5 4 0 6]
 [3 9 3 4 3]
 [6 1 1 0 0]
 [7 0 4 1 1]]
(5, 5)


In [186]:
# Reshaping Array

a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 4 3]
 [7 0 9]]
(2, 3)


In [190]:
b = a.reshape(3,2)
print(a)
print(a.shape)

[[0 4 3]
 [7 0 9]]
(2, 3)
